#!/bin/bash

shopt -s globstar nullglob extglob

for file in **/*.gif; do
    if [[ -f $file ]]; then
        file=${file##*/}
        file=${file%.gif}
        echo "$file"
    fi
done | LC_COLLATE=C sort -f

